import './sass/main.scss';
import './js/header';
import './js/main/main-cards';
import './js/main/movies-search';
import './js/modal';
import './js/footer/contributors';
import './js/spinner';
import './js/scrolling';
import './js/mylibrary';
